### ISSUE TITLE
Most optimal query string...

### ISSUE THREAD

**Issue by ingezone** [linq2db/linq2db.EntityFrameworkCore#104]
Hello 

Can you help me solve my next question, I need to determine which of the following two options is more optimal for my purpose.

I have to store data in MySQL that comes from IoT devices, finally I have to graph this data on a web page.

For each IoT device I need to store 3 variables in MySQL, these variables are accompanied by date and time and X and Y coordinates.

*** OPTION A ***
My first option A, is to build 3 separate tables for each variable (table #2a, #3a, #4a), table #1 contains the IoT devices with the respective X and Y coordinates. In this option, each table #2x will store in the base of data 3,153,600 rows for each year.

To obtain the data, I will use table #1 to filter the device of interest and I will make a JOIN with tables #2a, #3a, #4a to simultaneously graph the 3 variables with their respective date and time.

```
Table1:
> ------------+--------------+--------------+-----------+
>-  DeviceId -|-- Coord_X  --|--  Coord_Y --|- Enable  -|
> ------------+--------------+--------------+-----------+
>     D001    |      72.5    |     61.1     |     0     |
> ------------+--------------+--------------+-----------+
>     D002    |      77.1    |     64.8     |     1     |
```

```
TABLE 2a:					     TABLE 3a:						  TABLE 4a:
+--------+-------------------+---------+---------+   +--------+-------------------+---------+---------+   +--------+-------------------+---------+---------+
|-Value1-|----- Datetime ----|-Coord_X-|-Coord_Y-|   |-Value2-|----- Datetime ----|-Coord_X-|-Coord_Y-|   |-Value3-|----- Datetime ----|-Coord_X-|-Coord_Y-|
+ -------+-------------------+---------+---------+   + -------+-------------------+---------+---------+   + -------+-------------------+---------+---------+
|   32   |2021-01-16 00:00:00|   77.1  |   64.8  |   |   34   |2021-01-16 00:00:00|   77.1  |   64.8  |   |   29   |2021-01-16 00:00:00|   77.1  |   64.8  |
+ -------+-------------------+---------+---------+   + -------+-------------------+---------+---------+   + -------+-------------------+---------+---------+
|    :   |         :         |    :    |    :    |   |    :   |         :         |    :    |    :    |   |    :   |         :         |    :    |    :    |
+ -------+-------------------+---------+---------+   + -------+-------------------+---------+---------+   + -------+-------------------+---------+---------+
|   22   |2021-12-31 23:59:59|   77.1  |   64.8  |   |   25   |2021-12-31 23:59:59|   77.1  |   64.8  |   |   33   |2021-12-31 23:59:59|   77.1  |   64.8  |
+ -------+-------------------+---------+---------+   + -------+-------------------+---------+---------+   + -------+-------------------+---------+---------+
```

*** OPTION B ***
My second option B is to build 1 table that contains the 3 variables (table #2b), table #1 contains the IoT devices with the respective X and Y coordinates. In this option B, table #2 will store 3,153,600 in the database. rows for each year.

To obtain the data, I will use table #1 to filter the device of interest and make a JOIN with table #2 to simultaneously graph the 3 variables with their respective date and time.

```
Table1:
> ------------+--------------+--------------+-----------+
>-  DeviceId -|-- Coord_X  --|--  Coord_Y --|- Enable  -|
> ------------+--------------+--------------+-----------+
>     D001    |      72.5    |     61.1     |     0     |
> ------------+--------------+--------------+-----------+
>     D002    |      77.1    |     64.8     |     1     |
```

```
Table 2b:
+--------+--------+--------+-------------------+---------+---------+ 
|-Value1-|-Value2-|-Value3-|----- Datetime ----|-Coord_X-|-Coord_Y-| 
+ -------+ -------+ -------+-------------------+---------+---------+  
|   32   |   34   |   29   |2021-01-16 00:00:00|   77.1  |   64.8  | 
+ -------+ -------+ -------+-------------------+---------+---------+ 
|    :   |    :   |    :   |         :         |    :    |    :    |  
+ -------+ -------+ -------+-------------------+---------+---------+  
|   22   |   25   |   33   |2021-12-31 23:59:59|   77.1  |   64.8  |  
+ -------+ -------+ -------+-------------------+---------+---------+
```
ACCORDING TO WHAT I HAVE RESEARCHED, IT WOULD BE MORE EFFICIENT TO DO IT BY SEPARATE TABLES AS I MENTION IN MY OPTION A, but I'm not sure if I'm correct.

You can help me with your huge experience, once again I would be very grateful. :)

**Comment by sdanyliv** [comment]
Well, it needs research how do you plan to query that. And there are also tradeoffs. 
If values comes to databse together I'll prefer Option B, because JOIN is not free operation.
If values filed independently, better Option A for insert, but here we can get slowdown queries.

If you have to go with Option A - test your queries, it is simple, just fill database with fake data and check what is going. With linq2db it is several minutes to insert a lot of data.

**Comment by ingezone** [comment]
Thanks for the explanation, I took it into account when designing. 

Once again I thank you for your valuable help.

Best regards...
