### ISSUE TITLE
SUM does not coalesce

### ISSUE THREAD

**Issue by Atulin** [linq2db/linq2db.EntityFrameworkCore#135]
```cs
.Set(s => s.WordCount, s => s.Chapters
    .Where(c => c.IsPublished)
    .Sum(c => c.WordCount))
```

In this scenario, if no chapters are published, the result will be `null`. It cannot be coalesced with `??` since `Sum()` returns a non-nullable value, so there's no good way of giving this operation a default value of `0`.

The workaround is

```cs
.Set(s => s.WordCount, s => ((int?)s.Chapters
    .Where(c => c.IsPublished)
    .Sum(c => c.WordCount)) ?? 0)
```

but then the IDE complains that the left side of `??` will never be null.

**Comment by MaceWindu** [comment]
maybe `.Sum(c => (int?)c.WordCount)` ?

**Comment by Atulin** [comment]
It does appease the linter, yes, but it's still a workaround.

**Comment by MaceWindu** [comment]
If I understand your problem, that's a correct workaround. .net's `Enumerable.Sum` aggregate signature doesn't match same of sql `COUNT` and return non-nullable type when aggregated over non-nullable sequence.

**Comment by sdanyliv** [comment]
As designed.
