### ISSUE TITLE
about EntityFrameworkCore AsNoTracking()

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db.EntityFrameworkCore#14]
sometimes i want efcore no tracking for query faster ,
but this function is  in Microsoft.EntityFrameworkCore;
it has a conflict with linq2db

**Comment by sdanyliv** [comment]
Linq2db does not have such function. Do you experience some exception?

**Comment by quan01994** [comment]
我有可能没有表达清楚
是因为 Async methods 同时存在于linq2db 和 EntityFrameworkCore
so use linq2db and EntityFrameworkCore
i can not use async methods

**Comment by sdanyliv** [comment]
Why? I have done a lot of work to avoid such collisons. it’s not important which function is called, it will work for EF and linq2db also.

**Comment by quan01994** [comment]
I still write an example. -。-

**Comment by quan01994** [comment]
use linq2db async method to query data ,data will not be tracked by efcore?

**Comment by sdanyliv** [comment]
Why?

**Comment by quan01994** [comment]
sorry,my english is not very good.
能否帮我模拟AsNoTracking() 这个方法，来解决当一个类中同时引用linq2db和Microsoft.EntityFrameworkCore 产生的 异步方法产生二义性错误。

**Comment by sdanyliv** [comment]
I confirm problem. 
Unfortunately there is no way to solve conflict without breaking changes.

I have released linq2db.EntityFrameworkCore v 1.3.0, which contains additional functions: `ToListAsyncEF()`, `ToArrayAsyncEF()`, etc.

It should help if you have experienced such conflict.

**Comment by sdanyliv** [comment]
Already published solution.
