### ISSUE TITLE
BulkCopy stores System.Guid as byte[] rather than string with Sqlite

### ISSUE THREAD

**Issue by Nate129** [linq2db/linq2db.EntityFrameworkCore#141]
Hi,

I am attempting to write a join that compares the `Id` column of a given table with a string representation of  that column in another table like so:

``` c#

var query = from e in table
            join m in metadataTable on e.Id equals m.EntityId into metadata
            from m in metadata.DefaultIfEmpty()
            select m;

```

`EntityId` is a string representation of the `Id` column (in this case a `Guid`) as previously generated using `Id.ToString().ToUpper()` (I'm tracking history). 

The above query works if the items in the given `table` are previously inserted by EF Core. When Linq2db inserts the records with `BulkCopy`, it does not find a match by key. 

I observed the Sqlite file after the inserts completed, and with EF Core, the `Id` column for the test row had `14B2A952-AE6C-46A6-912F-A0140BC1A416` as its value.

When inserting with `BulkCopy`, the resulting `Id` column had the value set to `21,183,33,132,54,205,192,76,183,76,114,155,140,146,13,19`. 

Shouldn't Linq2db be storing the `string` representation of the `Guid` by default rather than the `string` representation of the `byte[]` representation of the `Guid`? 

Since Microsoft.Data.Sqlite and EF Core use `TEXT` as the data type for a Guid column when it comes to Sqlite, maybe that's involved causing this behavior somehow? Maybe Linq2db is expecting it be a `BLOB` data type column since EF Core used to do it that way...

If that is the intended behavior, how would I go about comparing the string representation of `Guid` in Linq2db? How should I format the string that goes into the `metadataTable` when it comes to `Guid`?

[Here](https://github.com/Nate129/Linq2dbBulkCopyIssue) is a repo which will generate sqlite database files that demonstrate the difference in the way `Guid` is stored. More details in the readme, including screenshots of results and sample sqlite db files.

Thank you!

**Comment by MaceWindu** [comment]
1. linq2db always mapped guid to binary for sqlite (https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/SQLite/SQLiteMappingSchema.cs#L52)
2. `Microsoft.Data.Sqlite` switched from binary to string mapping in v3

Technically it is possible to configure linq2db to use string mapping (probably `linq2db.EntityFrameworkCore` should do it for sqlite automatically), but it's a bit complicated:
- to change literal generation you need to set new conversion in mapping schema `ms.SetValueToSqlConverter(typeof(Guid),     (sb,dt,v) => 'here goes your guid to string conversion');`
- disable explicit cast of guid to byte[] when parameter used. As it currently done in provider implementation, you need to override this method https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/SQLite/SQLiteDataProvider.cs#L225

I think @sdanyliv will provide more details where to change mapping schema and how to use overriden provider with `linq2db.EntityFrameworkCore`

**Comment by Nate129** [comment]
I suppose linq2db stuck with the `BLOB` approach when `Microsft.Data.Sqlite` moved to string/`TEXT` for storing `Guid`. That explains why I couldn't get the join to work.

Will `linq2db.EntityFrameworkCore` be updated to automatically switch `Guid` storage to string mapping with Sqlite?

I'd appreciate any guidance @sdanyliv could provide for how to implement the workaround suggested by @MaceWindu in the meantime so I can keep moving forward one way or the other. 

Thanks guys!

**Comment by Nate129** [comment]
Hi, 

I tried to add the converter but it doesn't seem to like the generated SQL (I get an `unrecognized token` exception) with the following code:

``` c#
var connection = _context.CreateLinqToDbConnection();

connection.MappingSchema.SetValueToSqlConverter(typeof(Guid), (builder, c, v) => builder.Append(v);
```

Am I using the `StringBuilder` correctly by appending? I couldn't find any documentation that specified how the string should be applied to the `StringBuilder`, but an old issue regarding usage of `SetValueToSqlConverter` seemed to use it that way so I'm assuming that's right. 

I also couldn't find a way to apply the overridden `SQLiteDataProvider` class to my setup with EF Core- when using the extension method on my `DbContext` as demonstrated above, I can see the data provider as a property on the DbConnection but its setter is private, which means I'd have to get the custom class into the setup earlier than the extension method I'm using will allow. 

Any help would be appreciated- this is a bit of a blocker for me at the moment.

Any updates on whether or not this will be automatically configured by `linq2db.EntityFrameworkCore` in the future?

Thank you!

**Comment by MaceWindu** [comment]
1. `connection.MappingSchema.SetValueToSqlConverter(typeof(Guid), (builder, c, v) => builder.Append(v);` will produce something like `64690a33-c351-42cb-9b0a-c98bfd6d9b16`, but you need to generate string literal, enclosed in quotes:
```cs
builder.AppendFormat("'{0}'", v)
```

2. To replace provider with custom implementation, you need to override this method: https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs#L112 and register class with override here https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs#L88

**Comment by Nate129** [comment]
I can confirm that using `AppendFormat` fixes the 'unexpected token' error. Thanks for clearing that up. 

I can also confirm that your other suggestions worked as well.

With the following overriden SqliteDataProvider:

``` c#
public class GuidToStringSqliteDataProvider : SQLiteDataProvider
{
    public GuidToStringSqliteDataProvider(string name) : base(name)
    {
    }

    protected GuidToStringSqliteDataProvider(string name, MappingSchema mappingSchema) : base(name, mappingSchema)
    {
        }

        public override void SetParameter(DataConnection dataConnection, IDbDataParameter parameter, string name,
            DbDataType dataType, object value)
        {
            if (Name == ProviderName.SQLiteMS && value is Guid guid) 
                value = guid.ToString();

            base.SetParameter(dataConnection, parameter, name, dataType, value);
        }
    }
```

And the following class that uses the above provider:

``` c#
public class LinqToDbForEFToolsImplGuidToString : LinqToDBForEFToolsImplDefault
{
    protected override IDataProvider CreateLinqToDbDataProvider(EFProviderInfo providerInfo,
        LinqToDBProviderInfo provInfo, EFConnectionInfo connectionInfo)
    {
        return provInfo.ProviderName == ProviderName.SQLite
            ? new GuidToStringSqliteDataProvider(provInfo.ProviderName)
            : base.CreateLinqToDbDataProvider(providerInfo, provInfo, connectionInfo);
    }
}
```

And the following code to setup the DbConnection:

``` c#
private DataConnection GetDbConnection()
{
    LinqToDBForEFTools.Implementation = new LinqToDbForEFToolsImplGuidToString();

    var connection = _context.CreateLinqToDbConnection();

    connection.MappingSchema.SetValueToSqlConverter(typeof(Guid),
        (builder, c, v) => builder.AppendFormat("'{0}'", v));

    return connection;
}
```

The join in my original post is now working as expected. Thank you for taking the time to share that!

I may also need to have this configuration applied in a scenario where `linq2db.EntityFrameworkCore` is not being used. How would I setup `Linq2DB` to use the `GuidToStringSqliteDataProvider` class? I glanced at the code and the base class I inherit from to make my custom class is only used in private methods in the `SqliteTools` static class (according to GitHub), so there's no override option available there.

Thanks!

**Comment by MaceWindu** [comment]
- Pass provider instance to DataConnection constructor
or
- Register provider instance in DataConnection : https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/DataConnection.cs#L762

**Comment by Nate129** [comment]
Thanks for the tip(s), I will post back here if/when I get to that section of my project to verify that your suggestions did the job.

Just a quick update for anyone following along- I am currently able to continue using the workarounds provided above, with one change- I had to add `.ToUpper()` on Guid string conversions so that entities that were inserted with EF Core would work interchangeably with Linq2db.

I'll leave the issue open so it can be used for a PR if necessary.

Thanks for the help and your guys' hard work on Linq2db!
