### ISSUE TITLE
Is there a way to set the table name for a foreign table dynamically?

### ISSUE THREAD

**Issue by gaspropot** [linq2db/linq2db.EntityFrameworkCore#142]
For example:

```cs
var results = _dbContext.MyDbSet
    .ToLinqToDBTable().TableName($"my_{convention}")
    .LoadWithAsTable(p => p.GetForeignEntity).TableName($"my_ft_{convention}")
    .ToList()
```

**Comment by sdanyliv** [comment]
For which purpose? Maybe better to prepare several mapping schemas?
Currently there is no possibility to remap related entities on the fly.

**Comment by gaspropot** [comment]
Please let me explain the problem. What I am trying to do is select from a dynamic table, then include another dynamic table to my result which is related to the first table with a one-to-one relationship. 
So far I have managed to select from my first dynamic table by using the method .TableName($"{dynamic_table_name}"), and now for the next step I need to do something similar so that I include the second dynamic table that is related to the first one, like I try to do with the above linq query. Is there a way to do that?

**Comment by sdanyliv** [comment]
I would suggest only custom projection:
```cs
var query = 
    from p in _dbContext.MyDbSet.ToLinqToDBTable().TableName($"my_{convention}")
    from r in _dbContext.MyDbSet.ToLinqToDBTable().TableName($"my_ft_{convention}").LeftJoin(r => r.Parentid == p.Id)
    select new MyDbSet
    {
        Id = p.Id,
        ...
        GetForeignEntity = r
    };

var results = query.ToList();
```

**Comment by gaspropot** [comment]
I have decided to go with a different in order to reduce complexity. Thank you for trying to help anyways.
