### ISSUE TITLE
CreateTempTable returning entity in permanent table

### ISSUE THREAD

**Issue by Nate129** [linq2db/linq2db.EntityFrameworkCore#149]
Hi, 

I am attempting to copy an entity into a temporary table in order to do a bulk update operation from an in-memory collection. When attempting to populate the temporary table with an entity of the same type that exists and matches by `Id` in the main table, the temp table that is returned contains the entity as it exists in the main table, not the version of the entity that was supposed to be inserted into the temporary table.

The following test demonstrates the issue and fails on the current version of Linq2db/linq2db.EntityFrameworkCore:

``` c#
[Fact]
public void BulkCopy_Inserts_Correctly_When_Id_Exists_In_Permanent_Table_With_Same_Model_Type()
{
    var factory = new EFCoreSqliteInMemoryDbFactory();
    var context = factory.CreateDbContext<MainContext>();

    var person = new Person
    {
        Name = "John Doe"
    };

    context.Add(person);
    context.SaveChanges();

    var personCopy = new Person
    {
        Id = person.Id,
        Version = BitConverter.GetBytes(1),
        Name = "Jane Doe"
    };

    var connection = context.CreateLinqToDbConnection();

    var transaction = connection.BeginTransaction();

    var tempTable = connection.CreateTempTable(new List<Person> {personCopy},
        new BulkCopyOptions {KeepIdentity = true}, "PersonUpdate");

    transaction.Commit();

    var firstPerson = tempTable.First();

    firstPerson.Name.Should().Be(personCopy.Name);
    firstPerson.Version.Should().BeEquivalentTo(personCopy.Version, options => options.WithStrictOrdering());
}
```

A demo repo reproducing the issue can be found [here](https://github.com/Nate129/Linq2dbTempTableIssue). 

Thanks!

**Comment by Nate129** [comment]
Any news on this issue? It's becoming a blocker for me. 

Thanks!

**Comment by sdanyliv** [comment]
`CreateTempTable` has additional `TableOptions` parameter, set to `TableOptions.IsTemporary`.

**Comment by Nate129** [comment]
I tried your suggestion in the demo repo in the original post by changing the following code in all three tests: 

``` c#
 var tempTable = connection.CreateTempTable(new List<Person> {personCopy},
                new BulkCopyOptions {KeepIdentity = true}, "PersonUpdate", tableOptions: TableOptions.IsTemporary);
```

The test results did not change.

**Comment by Nate129** [comment]
Any other ideas?

**Comment by sdanyliv** [comment]
Oh, sorry missed your comment. Will check what happened. If it is an extension problem, will release new version tomorrow.

**Comment by Nate129** [comment]
No problem, sounds good, thanks!

**Comment by sdanyliv** [comment]
Well, not found time to look at. Moving to tomorrow.

**Comment by sdanyliv** [comment]
Well executed your sample. Everything is correct. Generated SQL:
```cs
--  SQLite

CREATE TEMPORARY TABLE [PersonUpdate]
(
	[Id]      TEXT NOT NULL,
	[Name]    TEXT     NULL,
	[Version] BLOB     NULL,

	CONSTRAINT [PK_PersonUpdate] PRIMARY KEY ([Id])
)

```

**Comment by Nate129** [comment]
I think the temporary table is being generated correctly as well; I agree with you. That's not where I was seeing the issue (as far as I can tell). The query is where things seem to go wrong (i.e. calling `First()` on the temp table) under certain conditions. 

I added a third test to better demonstrate the issue. Here's what the tests are meant to demonstrate: 

## Test 1

1. Add a new person (person 1) into (permanent) people table
2. Create a second person (person 2) with the same Id as the newly created person 1 but different values otherwise
3. Create a temp table and insert person 2 into it
4. Selecting the first person from the new temp table should return person 2

This test succeeds- it seems to be working correctly here (however I think this actually demonstrates a problem as explained later on).

## Test 2

1. Add a new person (person 1) into (permanent) people table
2. Create a second person (person 2) with a different Id and different values
3. Create a temp table and insert person 2 into it
4. Selecting the first person from the new temp table should return person 2

This test fails- the temp table `First()` query returned person 1 from the people table.

## Test 3

1. Add a new person (person 1) into (permanent) people table
2. Add a new person (person 2) into (permanent) people table
3. Create a second person (person 3) with a different Id and different values
4. Create a temp table and insert person 3 into it
5. Selecting the first person from the new temp table should return person 3

This test fails- the temp table `First()` query returned person 2 from the permanent table.


The first test correctly returning the temp table row and the second and third test incorrectly returning the permanent table row by Id suggests that the Id must already exist in the permanent table for the temp table query to work correctly. This is why I made the issue. 

There seems to be some problem that only occurs when the temp table type matches a permanent table type. 

Why would a query on temp table be returning entities from the permanent table under any circumstances? 

Thanks for looking into this!

**Comment by Nate129** [comment]
Could this be an issue with Sqlite? The query generated by the `First()` call generates: 

``` sql
SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[Version]
FROM
	[PersonUpdate] [t1]
LIMIT @take

```
Which does seem to be correct insofar as it is referencing the temp table and not the permanent table.

**Comment by sdanyliv** [comment]
Probably, problem with transaction. Can you try without Transaction or change Transaction scope?

**Comment by Nate129** [comment]
I removed all transaction code (`BeginTransaction()` and `transaction.Commit()`)  from all three tests and the test results were the same.

**Comment by sdanyliv** [comment]
Well, will look at this tomorrow. Too late here.

**Comment by Nate129** [comment]
Were you able to find some time to look at it?

**Comment by sdanyliv** [comment]
Tomorrow, a lot of work... Will check if it is SQLite issue.

**Comment by Nate129** [comment]
Sounds good, thanks!

**Comment by MaceWindu** [comment]
Didn't read into it carefully, have quick question - do you have non-temporary table with same name as created temporary table? If so - this is expected behavior for current linq2db version, as in such case you need to explicitly specify temporary schema for table in SQL or main table will be queried:

```sql
-- query main table
SELECT * FROM PersonUpdate
-- query main table
SELECT * FROM main.PersonUpdate
-- query temporary table
SELECT * FROM temp.PersonUpdate
```

In v4 I've fixed it (we always generate `temp` schema for temporary tables for SQLite) but fix wasn't backported to v3. If this is your porblem here - we will backport it for next release and as workaround you can set schema name to `temp` in `BulkCopyOptions`

**Comment by Nate129** [comment]
In the tests in the demo repo, the temp table is named `PersonUpdate` and EF Core names the permanent table `People`.

**Comment by sdanyliv** [comment]
I do not forgot about this issue. Debugging, something weird, really.

**Comment by sdanyliv** [comment]
Well, I have found bug.

Disable ChangeTracker `LinqToDBForEFTools.EnableChangeTracker = false;`

`AsNoTracking` support is also broken,

**Comment by Nate129** [comment]
Wow, good find.

I'll disable change tracking for now before the temp table create calls and enable it after the quey is

**Comment by Nate129** [comment]
Accidentally closed.

**Comment by Nate129** [comment]
I can confirm that clearing change tracking via `context.ChangeTracker.Clear();` before creating the temp table causes the tests to succeed in the demo repo. 

It would seem that the issue involves there being existing change tracking metadata for the entities being added to the temp table. It may also suggest that as long as there isn't metadata for the entity (by Id I assume) it might work ok.

**Comment by sdanyliv** [comment]
Fix already released.
