### ISSUE TITLE
Does not work with Pomelo provider

### ISSUE THREAD

**Issue by Mitch528** [linq2db/linq2db.EntityFrameworkCore#15]
[Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) uses [MySqlConnector](https://github.com/mysql-net/MySqlConnector) as opposed to MySql.Data, which is currently not supported by linq2db.

Attempting to use the Pomelo provider produces the following result:

```
FileNotFoundException: Could not load file or assembly 'MySql.Data, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

**Comment by sdanyliv** [comment]
Fixed in 1.6.0
