### ISSUE TITLE
Eager loading seems to not work with recursive CTEs?

### ISSUE THREAD

**Issue by Evengard** [linq2db/linq2db.EntityFrameworkCore#154]
Is it possible to use `.Include`/`.ThenInclude`, aka eager loading, for recursive CTEs? It seems that applying them on the query does absolutely nothing. Is it intended?

**Comment by sdanyliv** [comment]
Yes, it does nothing in current implementation. I have to find time for refactoring.

**Comment by sdanyliv** [comment]
Anyway better to show query.

**Comment by Evengard** [comment]
Is it even possible at all with Linq2db to do eager loading (LoadWith) with recursive CTEs?

**Comment by sdanyliv** [comment]
I have corrected your query and it should work. Currently recursive CTE cannot return whole object but only projection.
```cs
class DivisionCte
{
    public int DivisionId;
    public int ParentId;
}
```
```cs
var divisionCte = await _context.GetCte<DivisionCte>(d => 
    (
        from div in _context.Divisions
        where div.DivisionId == divId
        select new DivisionCte
        { 
            DivisionId = div.DivisionId
            ParentId = div.ParentId
        }
    )
    .Concat
    (
        from cdiv in _context.Divisions
        join pdiv in d on cdiv.ParentId equals pdiv.DivisionId
        selct new DivisionCte
        {
            DivisionId = cdiv.DivisionId,
            ParentId = cdiv.ParentId
        }
    ));

var query = 
    from d in _context.Divisions.Include(d => d.Employees)
    join cte in divisionCte on d.DivisionId equals cte.DivisionId
    select d;

var result = await query.ToArrayAsyncLinqToDB();
```

**Comment by Evengard** [comment]
That's interesting, I never thought about joining a recursive CTE for some reason. Thanks, will try.

**Comment by sdanyliv** [comment]
Why not ;) If you start thinking from SQL query but not from object collections perspective - it is natural way. And surprise, you will get almost the same SQL as a LINQ query.

**Comment by Evengard** [comment]
Thanks, that actually works on my much complex query as well! I really should think more out of the box with SQL... xD
