### ISSUE TITLE
Any plans to support EF Core 3?

### ISSUE THREAD

**Issue by adams85** [linq2db/linq2db.EntityFrameworkCore#18]
Hi!

I've been using this excellent lib to complement EF Core with great results. Now that EF Core 3 is out, it'd be great to upgrade so I did some tests but unfortunately LinqToDB integration is broken due to the changes of EF Core's internals.

I made a quick attempt at fixing the lib but I realized those changes were pretty extensive.

Do you have any plans to upgrade the integration lib anytime soon?

Best regards

**Comment by jogibear9988** [comment]
I‘ve one question, why combine ef core 3 with linq2db? are there still cases where ef core could not create sql where linq2db can, or is it about performance?

**Comment by adams85** [comment]
@jogibear9988 I combine them mainly because of this:

> you want to use advanced SQL functionality, not supported or poorly supported by EntityFrameworkCore like BulkCopy support, SQL MERGE operations, convinient DML (Insert/Delete/Update) operations and many-many-many other features LINQ To DB provides, but you need change tracking functionality that EntityFramework provides.

I'm browsing the new features of EF Core on [MSDN](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/index) but cannot see improvements regarding the above. Am I missing something?

I see though that the LINQ provider (LINQ to SQL translator) of EF Core 3 has been improved a lot but I cannot tell yet if it got better than LinqToDB's provider (which is pretty damn good in my experience).

**Comment by sdanyliv** [comment]
@adams85, I'll do that. I think we will start numbering from 2.0 to work with EF Core 3.0 and 1.X to support EF Core 2.X.

Thanks to pointing to these differences. We have to check them more often.

**Comment by adams85** [comment]
Great news, you're awesome, guys! :)

**Comment by hnviradiya** [comment]
How long may it take. Without a second thought about all libraries support, I upgraded mostly all libraries to .net core 3. and stopped working on this. My project depends a lot on this. :)

**Comment by adams85** [comment]
@hnviradiya I found a temporary solution - at least for my use case. The most important thing for me is to be able to re-use EF Core's O/R mapping so that I can continue using Code First and I don't have to specify a secondary mapping for LinqToDB. By using this method you can create a `DataConnection` object from a `DbContext` instance and access the LinqToDB features through the `DataConnection`. (Obviously, you lose the convenient API of the integration lib by doing this.)

```C#
public static class DbContextExtensions
{
	public DataConnection ToLinqToDBConnection(this DbContext context, IDataProvider provider, CancellationToken cancellationToken = default)
	{
		if (context == null)
			throw new ArgumentNullException(nameof(context));

		var mappingSchema = new MappingSchema();
		mappingSchema.AddMetadataReader(new EFCoreMetadataReader(context.Model));

		var transaction = context.Database.CurrentTransaction;
		if (transaction != null)
		{
			var dbTransaction = transaction.GetDbTransaction();

			if (!provider.IsCompatibleConnection(dbTransaction.Connection))
				throw new InvalidOperationException("LinqToDB cannot reuse connection because it provided by an unsupported ADO.NET provider.");

			return new DataConnection(provider, dbTransaction, mappingSchema);
		}
		else
		{
			var dbConnection = context.Database.GetDbConnection();

			return
				provider.IsCompatibleConnection(dbConnection) ?
				new DataConnection(provider, dbConnection, mappingSchema) :
				new DataConnection(provider, dbConnection.ConnectionString, mappingSchema);
		}
	}
}
```

To make this work, you'll also need a slimmed down version of [this class](https://github.com/linq2db/linq2db.EntityFrameworkCore/blob//bed1fa5d5241094a0fbd2d281f14191cf7ee4787/Source/LinqToDB.EntityFrameworkCore/EFCoreMetadataReader.cs).

BTW, right now the real showstopper is that MS replaced the ADO.NET provider of SQL Server (Microsoft.Data.SqlClient is used in EF Core 3 instead of System.Data.SqlClient) and LinqToDB supports only the old one. They can work side by side, but LinqToDB cannot reuse a connection opened by EF Core. Thus, you cannot mix EF Core and LinqToDB in a single transaction.

@sdanyliv  So [this is definitely a more urgent issue](https://github.com/linq2db/linq2db/issues/1895) right now.

**Comment by sdanyliv** [comment]
Sorry guys. I have already prepared new version. It will be released on monday-tuesday.

**Comment by hnviradiya** [comment]
Amazing...!!!

**Comment by sdanyliv** [comment]
I have prepared PR #19. It will be released tomorrow. 

There can be side effects when using with SQL Server `Include` (many) because of [bug in linq2db](https://github.com/linq2db/linq2db/pull/1922) and not yet supported latest provider `Microsoft.Data.SqlClient`. Current implementation will use old `System.Data.SqlClient` library to connect to the SQL Server, so we can not share connection between EF Core and linq2db. It may cause problems if you are trying to reuse started transaction.
We have plans to support `Microsoft.Data.SqlClient` but not before linq2db 3.0 release.

**Comment by sdanyliv** [comment]
Version 2.0 is released. Don't hesitate to post found issues because we use EF almost never.

**Comment by hnviradiya** [comment]
awesome. my project started working. Thanks a lot man.
