### ISSUE TITLE
Can not find private property 'RelationalQueryContextFactory._dependencies' in EF Core rc2

### ISSUE THREAD

**Issue by Mitch528** [linq2db/linq2db.EntityFrameworkCore#190]
After upgrading to EF Core rc2, I am encountering the following exception:

```
LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsException: Can not find private property 'RelationalQueryContextFactory._dependencies' in current EFCore Version.
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.GetCurrentContext(IQueryable query)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.ToLinqToDB[T](IQueryable`1 query)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFExtensions.ToListAsyncLinqToDB[TSource](IQueryable`1 source, CancellationToken token)
```

Packages:
linq2db - 3.5.0
linq2db.EntityFrameworkCore - 6.4.0
Microsoft.EntityFrameworkCore - 6.0.0-rc.2.21480.5
Pomelo.EntityFrameworkCore.MySql - 6.0.0-rc.1.ci.20211007223757

**Comment by sid-6581** [comment]
Will there be a new release with this fix when .NET 6 is released on November 9?

**Comment by sdanyliv** [comment]
We have released new version. But Pomelo still not ready.

**Comment by Mitch528** [comment]
> We have released new version. But Pomelo still not ready.

Pomelo is ready now but now there's a new problem, will create a new issue.
