### ISSUE TITLE
Runtime exception: apparent dependency problem with linq2db.EntityFrameworkCore package version 6.6.0

### ISSUE THREAD

**Issue by nathan-alden-sr** [linq2db/linq2db.EntityFrameworkCore#202]
I just tried upgrading `linq2db.EntityFrameworkCore` to 6.6.0 followed by a complete solution rebuild. The compile worked, but at runtime `LinqToDBForEFTools.Initialize()` throws an exception claiming it can't find `linq2db` version 3.5.2. This is strange, because according to NuGet, `linq2db.EntityFrameworkCore` version 6.6.0 references version 3.5.1 of `linq2db`. If I rollback to 6.5.0 and rebuild again, the code works perfectly.

![image](https://user-images.githubusercontent.com/1189759/141664393-210e2f1b-8cd6-4c48-89db-72c30dfa1949.png)
![image](https://user-images.githubusercontent.com/1189759/141664395-fb980337-ac57-4afd-8100-5514c192aeaa.png)
![image](https://user-images.githubusercontent.com/1189759/141664406-ed51c0a0-3a51-49d9-b836-51c76a00fc68.png)

**Comment by MaceWindu** [comment]
looks like @sdanyliv forgot to update linq2db version in nuspec and nuget still reference 3.5.1. It should work if you install 3.5.2 manually

**Comment by MaceWindu** [comment]
fixed version (6.6.1) released
