### ISSUE TITLE
Integration with MiniProfiler

### ISSUE THREAD

**Issue by michalsznajder** [linq2db/linq2db.EntityFrameworkCore#227]
Is there a way to integrate `linq1db.EntityFrameworkCore` with [MiniProfiler](https://miniprofiler.com/)?

Regular `linq2db` has `DataContext` wrapper example on [linq2db.github.io](https://linq2db.github.io/) but I am not sure how to apply this when using this bridge.

**Comment by MaceWindu** [comment]
You can register required interceptor using `AddInterceptor` configuration API.

`MiniProfiler` interceptor example could be found [here](https://linq2db.github.io/articles/general/interceptors.html#iunwrapdataobjectinterceptor)
