### ISSUE TITLE
MySql Pomelo - Mapping Parent child...

### ISSUE THREAD

**Issue by sathyakrishnan** [linq2db/linq2db.EntityFrameworkCore#254]
Hi,
We're trying to use the package with MySQL and Pomelo. We have a parent -> child1 -> child2 -> child3 scenario.
We tried BulkCopyAsync but only parent is getting populated.  Is there any settings required that we are missing which ensures that the child entities are populated as well.

**Comment by sdanyliv** [comment]
BulkCopy inserts only into one table using low level provider’s commands. Other tables should be BulkCopied separately.

**Comment by sathyakrishnan** [comment]
Thanks for the prompt response. If we copy separately, how can we get the parent id to copy to child entities.

**Comment by viceroypenguin** [comment]
You cannot with `BulkCopy`. To use  `BulkCopy` in this way, you will need to pre specify your own IDs in the C# code. 

Alternatively, you can use `InsertWithOutput`. You will still have to call separately for each table, but you can get the ID value for each inserted record.

**Comment by Shane32** [comment]
Per MS note:

> SQL Server does not guarantee the order in which rows are processed and returned by DML statements using the OUTPUT clause. It is up to the application to include an appropriate WHERE clause that can guarantee the desired semantics, or understand that when multiple rows may qualify for the DML operation, there is no guaranteed order.

**Comment by Shane32** [comment]
I’d probably think about how to bulk copy the tables into temp tables, then execute queries to insert/merge to the destination tables. Bulk copy is just so much faster than not typically.

**Comment by sathyakrishnan** [comment]
Thanks for the insights.
