### ISSUE TITLE
Compatible with EF Core 7?

### ISSUE THREAD

**Issue by jaglick** [linq2db/linq2db.EntityFrameworkCore#262]
I'm working on migrating to EF Core 7. When I call ToListAsyncLinqToDB I receive the following exception:

Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.Query.QueryRootExpression.get_EntityType()'.

My query also contains a temp table, created via a call to context.CreateTempTable.

**Comment by sdanyliv** [comment]
Not yet. We will prepare new version in several days.

**Comment by jaglick** [comment]
Sounds good, thanks!

**Comment by sdanyliv** [comment]
Just released.
