### ISSUE TITLE
Dependencies warning

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db.EntityFrameworkCore#3]
warning NU1603: linq2db.EntityFrameworkCore 1.0.0 依赖于 linq2db (>= 2.1.0-rc2453)，但找不到 linq2db 2.1.0-rc2453。 已解决 linq2db 2.1.0 的近似最佳匹配。

**Comment by sdanyliv** [comment]
Thanks for reporting will fix this ASAP.

**Comment by sdanyliv** [comment]
Version  1.0.1 already on nuget.
