### ISSUE TITLE
UnwrapDataObjectInterceptor not beign called

### ISSUE THREAD

**Issue by michalsznajder** [linq2db/linq2db.EntityFrameworkCore#306]
I was trying to integrate MiniProfiler with linq2db.EF and in #227 it was suggested to use `UnwrapDataObjectInterceptor` for this.

I tried following simple scenario:
```c#
public class DummyInterceptor : UnwrapDataObjectInterceptor
{
    public override DbConnection UnwrapConnection(IDataContext dataContext, DbConnection connection)
    {
        return connection;
    }

    public override DbTransaction UnwrapTransaction(IDataContext dataContext, DbTransaction transaction)
    {
        return transaction;
    }

    public override DbCommand UnwrapCommand(IDataContext dataContext, DbCommand command)
    {
        return command;
    }

    public override DbDataReader UnwrapDataReader(IDataContext dataContext, DbDataReader dataReader)
    {
        return dataReader;
    }
}

services.AddDbContext<MyContext>(options =>
{
    options.UseNpgsql(Configuration.GetConnectionString("Context"));

    options.UseLinqToDB(o =>
    {
        o.AddInterceptor(new DummyInterceptor());
    });
});
```

When executing 
```c#
var result = await _myContext.Table
            .ToLinqToDB()
            .ToListAsyncLinqToDB();
```

only method ```UnwrapDataReader``` is called. Is there a way to get method ```UnwrapConnection``` to be called?

**Comment by michalsznajder** [comment]
Interceptor is used but not all methods are called. I just tried your test and `interceptor.Count` has value of 1. Only method `UnwrapDataReader` is called. For integration of  MiniProfiler I require  `UnwrapConnection` to be called. Or at least this is my idea.

Can you confirm that my observation of only one method being called is correct?

**Comment by MaceWindu** [comment]
miniprofiler wrappers implement ADO.NET API by redirecting calls to wrapped object, so in general we call unwrap only when we need to work with provider-specific APIs, not awailable in ADO.NET

**Comment by MaceWindu** [comment]
Note that unwrapping miniprofiler unconditionally will make it useless, as it will not be able to intercept and profile ADO.NET calls

**Comment by michalsznajder** [comment]
Actually I wanted to do the opposite. I wanted to wrap connection in interceptor with `ProfiledDbConnection` from MiniProfiler.

MiniProfiler traces some internal events to profile EFCore (not by wrapping DbConnection in EFCore). Linq2DB.EFCore uses connection from EFCore so my idea was to use interceptor for decoration. I wanted to abuse this API as I see no other way of doing it.

**Comment by michalsznajder** [comment]
Bingo! I missed `CommandInitialized`. Following code is good enough.

```
public class MiniProfilerInterceptor : CommandInterceptor
{
    public override DbCommand CommandInitialized(CommandEventData eventData, DbCommand command)
    {
        return new ProfiledDbCommand(command, command.Connection, MiniProfiler.Current);
    }
}
```

Thank's.
