### ISSUE TITLE
linq2db.EntityFrameworkCore with 3.0.0.preview2

### ISSUE THREAD

**Issue by Marka83** [linq2db/linq2db.EntityFrameworkCore#34]
Is it possible to use it with 3.0.0.preview2?
It used to work with 2.9.7, but now it throws:

`System.MissingMethodException: 'Method not found: 'Boolean LinqToDB.DataProvider.IDataProvider.IsCompatibleConnection(System.Data.IDbConnection)'.'
`

when I call 

`source.ToLinqToDB()`

I have over 1.5k classes so I can't just swap all of them at the same time.
That is why I've tried to use this adapter as a intermediate solution.

**Comment by sdanyliv** [comment]
Sorry about that I'll prepare release today. It will be version 3.0 because of important API changes in linq2db 3.X

**Comment by Marka83** [comment]
Thank you

**Comment by Marka83** [comment]
Any update on this?

**Comment by sdanyliv** [comment]
Sorry, almost done. I’ve added a lot of improvements, testing.

**Comment by sdanyliv** [comment]
Sorry for delay agin, I was underestimated needed changes.
linq2db.EntityFrameworkCore 3.0 already on Nuget. Let me know if there are any problems.

**Comment by Marka83** [comment]
Everything works great. Thanx
