### ISSUE TITLE
Support for "MERGE INTO tablename USING dual ON ..." (UPSERT functionality) with  Oracle.ManagedDataAccess.Core

### ISSUE THREAD

**Issue by abrasat** [linq2db/linq2db.EntityFrameworkCore#341]
Is it possible to use the extension library to generate a sql query for oracle using Oracle.ManagedDataAccess.Core, that looks like in this [example](https://stackoverflow.com/questions/237327/oracle-how-to-upsert-update-or-insert-into-a-table/27906848#27906848)?
```
MERGE INTO tablename USING dual ON ( val3 = in_val3 )
WHEN MATCHED THEN UPDATE SET val1 = in_val1, val2 = in_val2
WHEN NOT MATCHED THEN INSERT 
    VALUES (in_val1, in_val2, in_val3)
```
Can somebody please post a code snippet with the correct syntax?
Is it possible to use the extension only for choosen ef core generated queries?

**Comment by abrasat** [comment]
This worked indeed, thank you very much!
How can I see the generated sql query string?

**Comment by viceroypenguin** [comment]
Yes, MergeAsync as the final method will be an async method for you. 

You can check `_context.LastQuery` to see the most recently completed statement executed by that db context.

**Comment by abrasat** [comment]
Thanks for the information.
I could not find a LastQuery property in my DbContext

**Comment by viceroypenguin** [comment]
Sorry, I was thinking of the Linq2Db `DataConnection`. You'll probably need to add an interceptor that will let you log the query, or attach a profiler to the database.

**Comment by abrasat** [comment]
Ok, I will look for it, thx.
