### ISSUE TITLE
IMergeable.UpdateWhenMatched: How can I provide custom setters for SOME of the fields, and use default for others

### ISSUE THREAD

**Issue by bt-88** [linq2db/linq2db.EntityFrameworkCore#362]
### As is
Currently, for merge operations, you provide two overloads:

* `UpdateWhenMatched()`: Updates all fields that are in both source and target
* `UpdateWhenMatched(Expression<Func<TTarget,TSource,TTarget>> setter)`: Updates the fields as specified in the user defined setter

### To be
What I would like to have is a _combination of both_. That is, it updates all fields that are in both source and target AND applies the custom 'overrides' for some of the fields.

### Use case
Use case. Have user defined setters for the `UpdatedAt` and `CreatedAt` fields in my base entity, but use the default update setters for all other fields.

```csharp
.UpdateWhenMatched((target,source)=> new TTarget
            {
                CreatedAt = target.FusionCreatedAt,
                UpdatedAt = DateTime.UtcNow,
                // Use defaults for all other fields without the need to specify them explicitly
            });
```

The same applies to `.InsertWhenNotMatched`. Here I would like to do:

```csharp
.InsertWhenNotMatched( _ => new TTarget { CreatedAt = DateTime.UtcNow, // Use defaults for all other fields without the need to specify them explicitly })
```

**Comment by bt-88** [comment]
Anyone? If someone can guide me in the right direction I'm willing to draft a PR for this.

**Comment by sdanyliv** [comment]
Sorry for delay, it needs API design, not simple thing right now. I can help you to write such method without changing `linq2db` code.

**Comment by bt-88** [comment]
> Sorry for delay, it needs API design, not simple thing right now. I can help you to write such method without changing `linq2db` code.

Thank you, that would be awesome. Please show me how when you have the time.

**Comment by bt-88** [comment]
> I assume it should work only if `TSource` and `TTarget` are the same?

Yes, correct.

**Comment by sdanyliv** [comment]
Added answer in linq2db repository.
