### ISSUE TITLE
Library broken with Projectables

### ISSUE THREAD

**Issue by AntonC9018** [linq2db/linq2db.EntityFrameworkCore#364]
I understand that this issue might be outside the scope and you might not care to support it. I'm trying to use the library in combination with [this](https://github.com/koenbeuk/EntityFrameworkCore.Projectables). It fails in the code that uses reflection to extract `DbContext` from `IQueryable` because of an invalid cast to `QueryCompiler` (that lib defines a custom query compiler). [Here it is](https://github.com/koenbeuk/EntityFrameworkCore.Projectables/blob/4a8390565d5a8987ea6612c5c555afd35e2266dc/src/EntityFrameworkCore.Projectables/Infrastructure/Internal/CustomQueryCompiler.cs#L16).
Should we perhaps push the EF Core team to add API's for this?
I guess a workaround that I could do is that I could override that method in a custom impl of that class, since the method's virtual.

**Comment by MaceWindu** [comment]
@sdanyliv , it looks to me that `LinqToDBForEFTools.Implementation` assignment should trigger re-initialize, which is not possible with current code due to Lazy already triggered.

**Comment by AntonC9018** [comment]
Do we have a workaround for this? Setting the implementation before `Initialize` doesn't help either.

**Comment by AntonC9018** [comment]
> @sdanyliv , it looks to me that `LinqToDBForEFTools.Implementation` assignment should trigger re-initialize, which is not possible with current code due to Lazy already triggered.

No, sorry, it works. I was instantiating the wrong class, that's why. I've fixed the code in the comment.

**Comment by MaceWindu** [comment]
I don't think there is something for us to change - `virtual GetCurrentContext` is a proper place to support custom compilers.

Btw, probably it even will work with new projectables releases out-of-box as side-effect of this change https://github.com/koenbeuk/EntityFrameworkCore.Projectables/issues/110
