### ISSUE TITLE
Warning Message for CreateLinqToDbConnection Method

### ISSUE THREAD

**Issue by fthkr** [linq2db/linq2db.EntityFrameworkCore#376]
https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/3f39e42adc124a41d0a814041932325a71c29db5/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs#L250

I'm using this method to begin transaction with linq2Db:
```
     using (var linq2Db = _myContext.CreateLinqToDbConnection())
     {
         linq2Db.BeginTransaction();
     .
     .
     .
```
When I use this method, I take warning message like this "... method is obsolete: Use CreateLinqToDBConnection overload." These methods name and parameters are same. How can I get rid of this warning message?

**Comment by jods4** [comment]
Not the same, `DB` with a capital `B`
https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/3f39e42adc124a41d0a814041932325a71c29db5/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFTools.cs#L262
