### ISSUE TITLE
Not logging generated sql

### ISSUE THREAD

**Issue by forik** [linq2db/linq2db.EntityFrameworkCore#38]
Hi, I'm not sure is that by design or not but no sql is being logged. 
For example, then request to web app starts some of queries are executed using EF Context, and some with linq2db extensions over EF Context, so the latter queries not logged. 
Probably something needs to be setup?

**Comment by sdanyliv** [comment]
No, it should be logged automatically if you specify logger for EF Core DbContext.
Could you please prepare simple reproduce solution?

**Comment by forik** [comment]
> 
> 
> No, it should be logged automatically if you specify logger for EF Core DbContext.
> Could you please prepare simple reproduce solution?

I managed to get it working. I'm using Serilog integration and I wasn't explicitly calling UseLoggerFactory on DbContext options builder, so Options property didn't have LoggerFactory. 
After I added the call everything started to work. Closing.

**Comment by RouR** [comment]
For anyone who have same issue: Don't foget to call 
`DataConnection.TurnTraceSwitchOn();`
https://github.com/linq2db/linq2db/issues/646
