### ISSUE TITLE
BulkCopy not converting Guids to binary(16) on MariaDB

### ISSUE THREAD

**Issue by HenriqueSabino** [linq2db/linq2db.EntityFrameworkCore#394]
I have a MariaDB database with the setting `GuidFormat=Binary16` on the connection string so that Guids are stored in binary format. But after running the `BulkCopy` command I get this exception:

```
MySqlConnector.MySqlException (0x80004005): Data too long for column 'columName' at row 1
``` 

Meaning that the the Guid wasn't converted properly.

I tried setting up the MappingSchema with `AddScalar(typeof(Guid), DataType.Binary)` but it didn't work. Am I missing something?

**Comment by HenriqueSabino** [comment]
Got it working with this
```cs                    
opt.UseLinqToDB(opt =>
{
    var mappingSchema = new MappingSchema();
    var mapper = new FluentMappingBuilder(mappingSchema);

    mapper.Entity<MyModel>()
        .Property(x => x.GuidProperty)
        .HasConversion(x => x.ToByteArray(), s => new Guid(s))
        .Build();

    opt.AddMappingSchema(mappingSchema);
});
```

**Comment by HenriqueSabino** [comment]
Btw, is there a way to apply this rule to all Guids?

**Comment by sdanyliv** [comment]
I have not a lot of time to explain, but try `SetConvertExpression`
