### ISSUE TITLE
.NETStandard 2.0 dependency

### ISSUE THREAD

**Issue by zdomokos** [linq2db/linq2db.EntityFrameworkCore#43]
EF core is dependent on .NETStandard 2.0, allowing .net framework to use both ef core and linq2db.
Would it be possible to switch back to .NETStandard 2.0 so this great package could be used from .net framework applications too. Thanks.

**Comment by MaceWindu** [comment]
Not sure I understand problem. linq2db supports netstandard2.0 target

**Comment by zdomokos** [comment]
linq2db.EntityFrameworkCore nuget package dependency is .NETStandard 2.1 so cannot be used in .net framework 4.8, while linq2db and efcore can be used.

**Comment by sdanyliv** [comment]
Released in 3.1.0
