### ISSUE TITLE
Add to EFCore Extensions page

### ISSUE THREAD

**Issue by Arithmomaniac** [linq2db/linq2db.EntityFrameworkCore#48]
You can edit the page and make a PR. Great way to promote, and in particular, to highlight the [unique features](https://github.com/linq2db/linq2db.EntityFrameworkCore#why-should-i-want-to-use-it).
https://docs.microsoft.com/en-us/ef/core/extensions/

**Comment by sdanyliv** [comment]
Added Unique features section. Not too much?

**Comment by Arithmomaniac** [comment]
Looks like most of them are shorter. Maybe like:

> Alternative translator of LINQ queries to tracking-free SQL expressions.
>
> Includes support for advanced SQL features such as CTEs, bulk copy, table hints, windowed functions, temporary tables, and database-side create/update/delete operations.

Also, as noted in [your issue](https://github.com/dotnet/EntityFramework.Docs/issues/2411), you need to edit and submit as PR.

**Comment by sdanyliv** [comment]
Will do that, thanks for short description.

**Comment by sdanyliv** [comment]
PR Submitted
