### ISSUE TITLE
about fromsql 

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db.EntityFrameworkCore#5]
I use linq2db.EntityFrameworkCore in a class, then i can not use `Db.Query<T>().FromSql("sql")`;
`FromSql` method in Microsoft.EntityFrameworkCore; 
What's the better solution?

**Comment by sdanyliv** [comment]
Usually better to show which SQL you are expecting as the result.

**Comment by quan01994** [comment]
i try convert sql to linq .
When you have a problem, come back to you to discuss,
thank you.

**Comment by quan01994** [comment]
````
                 var qry = from order in db.OrderInfo
                    from goods in db.GoodsInfo.LeftJoin(or => or.GoodsCode == order.GoodsCode)
                    where orderNos.Contains(order.OrderNo)
                    select new GoodsInSaleOrderOutput
                    {
                        OrderNo = order.OrderNo,
                        GoodsId = goods.GoodsId,
                        GoodsLevelName = goods.GoodsLevelName,
                        GoodsName = goods.GoodsName,
                        GoodsPic = goods.GoodsPic,
                        GoodsSize = goods.GoodsSize,
                        SalePrice = goods.SalePrice,
                        SaleQnty = order.SaleQnty,
                        SaleWay = order.SaleWay,
                        Status = goods.Status
                    };
                var temp = qry.OrderBy(m=>m.OrderNo).Skip(1).Take(2).ToLinqToDB().ToList();  //first query
                var count = qry.ToLinqToDB().Count(); //second query
````
![tim 20180801134629](https://user-images.githubusercontent.com/20533465/43503417-d2a4c2fa-9591-11e8-9bbe-99711e74f485.png)

between fisrt and second , throw many sql exception ,why 。
about sa login fail

**Comment by sdanyliv** [comment]
What is `orderNos` ? If it is not array or list - it can be problem.

**Comment by quan01994** [comment]
@sdanyliv  
 var orderNos = new List<string> { "0002201803310052", "0002201804160026" };

**Comment by sdanyliv** [comment]
I have no idea what happened here, as i know we are not activated retry policy here. Maybe you have some background tasks, Which also can do requests.
Whithout callstack it is almost impossible to solve.

**Comment by sdanyliv** [comment]
Press Ctr+Alt+E
And set `Break When Thrown` check box for all `Common Language Runtime Exceptions`

**Comment by quan01994** [comment]
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=用户 'sa' 登录失败。
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

**Comment by quan01994** [comment]
This is very strange 
first query is successed.
then throw  sqlserver login fail
try many times  util second query successed

**Comment by sdanyliv** [comment]
Will check

**Comment by sdanyliv** [comment]
@quan01994, do you still have such problems? I can not reproduce this.

**Comment by sdanyliv** [comment]
Closing for now, will reopen if needed.
