### ISSUE TITLE
Console logging with PomeloMySql

### ISSUE THREAD

**Issue by sabvente** [linq2db/linq2db.EntityFrameworkCore#51]
Hello,

I have a working query logging for EF, but my recursive cte query with linq2db doesn't gets logged.

This is my appsettings.json (this is all log config as far as I know):
```
"Logging": {
    "LogLevel": {
      "Microsoft.EntityFrameworkCore.Database.Command": "Information"
    }
  }
```

How can I turn on console logging?

**Comment by sdanyliv** [comment]
Maybe I have missed something about EF Core Logging. But if you `.UseLoggerFactory(MyLoggerFactory)` in your `DbContext` - logging should work.

**Comment by sdanyliv** [comment]
Closing since there is no additional input.
