### ISSUE TITLE
Support In-Memory Database

### ISSUE THREAD

**Issue by idubnori** [linq2db/linq2db.EntityFrameworkCore#6]
Throw exception, if use `UseInMemoryDatabase` in `Microsoft.EntityFrameworkCore.InMemory`.
```
System.InvalidCastException: 
'Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryContextFactory' 
'Microsoft.EntityFrameworkCore.Query.RelationalQueryContextFactory'
```

**Comment by sdanyliv** [comment]
We do not have plans to support in-memory database. Think about linq2db usage as stored procedure execution.
Main linq2db goal is to generate complex SQL and run query effectively as posssible. In-memeory database is just mock for unit testing and supports almost nothing from SQL world.

**Comment by idubnori** [comment]
Got it. Thank you. To throw `NotSupportedException`, needs to fix in linq2db side?

**Comment by sdanyliv** [comment]
Yes, not closing this issue to track that we have to add such exception.
Thanks.

**Comment by jogibear9988** [comment]
This means a special EF core in memory mode? Sqlite inmemory is supported?

**Comment by idubnori** [comment]
@jogibear9988 Yes. Sqlite with in-memory looks good to me. (Just checked `DeleteAsync` only)

**Comment by sdanyliv** [comment]
@idubnori, we are not EF users, so any feedback is valuable.

**Comment by sdanyliv** [comment]
Added more informative message instead of `InvalidCastException` in cf1bbf4e476e43067cd3723b221f301eb79ff258
