### ISSUE TITLE
Entity Framework 5 Support?

### ISSUE THREAD

**Issue by majbo** [linq2db/linq2db.EntityFrameworkCore#71]
EF Core 5.0 will be released this month, RC1 & RC2 are already available.  I'm eager to use some new EF Core 5.0 features, but the lacking support of linq2db.EntityFrameworkCore holds me back.

From what I saw there is at least one breaking change -> `Microsoft.EntityFrameworkCore.RelationalQueryableExtensions.FromSqlOnQueryable` 
does not longer exist. It is used in `LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.GetContextOptions`.

Is anybody having a look at 5.0 compatibility? Is there maybe an ETA?

**Comment by sdanyliv** [comment]
So, first request about EF Core 5 ;) Will create new version in few days.

**Comment by sdanyliv** [comment]
As a little quiz. Which functionality from this extension do you use?

**Comment by majbo** [comment]
I'm using the common table functions for recursive queries.

**Comment by sid-6581** [comment]
I'd also love to see EF Core 5 support! I mainly use bulk operations (insert etc.)

**Comment by sdanyliv** [comment]
@sid-6581, will try to release tomorrow. No worries, there is a small CI issues.

**Comment by MaceWindu** [comment]
Released https://www.nuget.org/packages/linq2db.EntityFrameworkCore

**Comment by sid-6581** [comment]
Thanks for getting that done so quickly! However, when I try using the new nuget package I get this warning:

`WARNING: NU1701: Package 'linq2db.EntityFrameworkCore 5.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.`

I don't even see how that is possible since I don't even see those as valid target frameworks?

**Comment by Shane32** [comment]
@sid-6581 Which framework does your application use?

@MaceWindu  @sdanyliv  I didn't think of it before, but EF5 support shouldn't target net5.  EF5 is supported on .Net Standard 2.1 platforms, such as .Net Core 3.1, and should therefor target .Net Standard 2.1

https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-ef-core-5-rc2/

> **EF Core 5.0 will not run on .NET Standard 2.0 platforms, including .NET Framework.**
> The release candidates of EF Core 5.0 require .NET Standard 2.1.
> This means that EF Core 5.0 will run on .NET Core 3.1 and does not require .NET 5.
> To summarize: EF Core 5.0 runs on platforms that support .NET Standard 2.1.

**Comment by Shane32** [comment]
Nuget says this is already the case, actually, and looking at the code and error message posted above this is a puzzling error.

**Comment by sid-6581** [comment]
@Shane32 My applications target net5.0. As far as I can tell, this library targets netstandard2.1, so is this just a spurious nuget warning? It's odd though, this is the only library I'm getting a warning for out of all my dependencies.

**Comment by Shane32** [comment]
I don't think it should give you that warning.  I checked the package and its dependencies with NuGet Package Explorer and can't find anything wrong with them (as it relates to this issue).  I'll see if I can do some more testing over the weekend.

**Comment by MaceWindu** [comment]
@sid-6581 sorry about that, fixed version will be published in 10 minutes

**Comment by sid-6581** [comment]
That worked great, thanks guys so much for your quick responses! This library is a lifesaver. 😊
