### ISSUE TITLE
[net5.0] Using OrderBy followed by ThenBy inside RowNumber results in swapped columns for sorting

### ISSUE THREAD

**Issue by lokalmatador** [linq2db/linq2db.EntityFrameworkCore#83]
Using both `OrderBy`and `ThenBy` inside `RowNumber` in a Linq2Db query results in an erroneous raw SQL query where the columns used in `OrderBy` and `ThenBy` are swapped, i.e.,` ...Sql.Ext.RowNumber().Over().OrderBy(A).ThenBy(B)...` results in the following erroneous query string like `...ROW_NUMBER() OVER(ORDER BY B, A)...`.

Here's an MWE with two test cases demonstrating the issue: [Linq2DbMWE.zip](https://github.com/linq2db/linq2db.EntityFrameworkCore/files/5603426/Linq2DbMWE.zip)

It was working before updating to net5.0.

**Comment by sdanyliv** [comment]
@lokalmatador, sorry about that. We already fixed this regression but not released yet. 
But you can connect to Azure Pipelines Nuget feed and get latest linq2db version

https://dev.azure.com/linq2db/linq2db/_packaging?_a=feed&feed=linq2db

**Comment by sdanyliv** [comment]
https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops#windows-add-the-feed-to-your-nuget-configuration
