### ISSUE TITLE
[Question] Correct resources cleanup

### ISSUE THREAD

**Issue by forik** [linq2db/linq2db.EntityFrameworkCore#84]
Hi,

Please help me understand, how does linq2db.EntityFrameworkCore integration cleans up created DataConnection? I see that extensions methods, e.g. ToLinqToDB(), create a linqToDb DataConnection which is IDisposable, but seems like created DataConnection not being diposed and thus connection or command could leak. 
Am I wrong? Does the integration fully relies on EF Core's connection management?

Thanks

**Comment by sdanyliv** [comment]
Yes, it tries to reuse EF Core`s connection management.

**Comment by forik** [comment]
Thanks, closing
