### ISSUE TITLE
`ToListAsync` overlaps with EF's extensions

### ISSUE THREAD

**Issue by Nican** [linq2db/linq2db.EntityFrameworkCore#85]
When using `Microsoft.EntityFrameworkCore` and `LinqToDB` on the same file, and attempt to invoke `ToListAsync`, you get an error:
> The call is ambiguous between the following methods or properties: 'Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync<TSource>(System.Linq.IQueryable<TSource>, System.Threading.CancellationToken)' and 'LinqToDB.AsyncExtensions.ToListAsync<TSource>(System.Linq.IQueryable<TSource>, System.Threading.CancellationToken)'

I am not sure what the best of solving this, but as a temporary work around, I am creating my own static class, on my own namespace, that only exports the necessary non-conflicting extensions that I need. Such that when using `Microsoft.EntityFrameworkCore` and `MyNamespace`, I can still use LinqToDB and EF on the same file.

Any other ideas on how to fix this? Or how are other people dealing with the conflicting extension methods?

**Comment by sdanyliv** [comment]
There are `ToListAsyncEF()` and `ToListAsyncLinqToDB()` for resolving such collision.

**Comment by Nican** [comment]
Oh- Thank you so much for the quick response. My sincere apologies. I should have looked closer at the README.
