### ISSUE TITLE
[Question] Fast Eager Loading (incomparable faster on massive Include query)

### ISSUE THREAD

**Issue by rekosko** [linq2db/linq2db.EntityFrameworkCore#86]
Hi there. In my project we have quite a lot of includes when querying items from database. After switching one of internal projects to .netcore3.1 we had to refactor a little bit every query to have fewer includes and then also use `LoadAsync()` this is horrible and painful.

I just wanted to ask "how many includes this lib can handle?". Don't get me wrong but we have like 22 includes (I've just counted includes (but there are more with `ThenInclude()` - I've just gave a general number of main includes) and it seems the app hangs out at generating db query for few minutes now...

I know the number of includes is ridiculous but please... don't judge :) There are more than 40ppl working on those projects and quality is not always the thing.

**Comment by sdanyliv** [comment]
Just try. When implementing Eager Loading mechanism, I didn't introduce any limitations. Really interesting to see what will be generated ;)

**Comment by rekosko** [comment]
I've removed all `.ThenInclude()` and after 1min30secs I got a set of queries that ran successfully. Following same queries but with different Id's also ran instantly.

It seems that it's having difficulties with nested includes because the queries are generating for ages.

**Comment by sdanyliv** [comment]
If you prepare sample project for me, I can check what we can do with performance here. Anyway 22 includes is crazy ;)

**Comment by rekosko** [comment]
I know it's crazy but well... it happens :) I will try and prepare something but probably after new year :)

**Comment by sdanyliv** [comment]
Real cases will be helpful. I do not need data, just model and your query.

**Comment by ingezone** [comment]
li will check and let you know.

**Comment by coderdnewbie** [comment]
This could be the Cartesian Explosion problem. EF Core 5.0 introduces the feature ‘AsSplitQuery()’ to resolve the problem but the EF Team says there are edge cases where this feature can cause problems. The amount of includes suggests to me that the Cartesian Explosion problem may be the cause of the performance issue.

**Comment by sdanyliv** [comment]
This extension works as `AsSplitQuery` but better. `AsSplitQuery` won't work with custom projection.

**Comment by coderdnewbie** [comment]
In EF Core 6, AsSplitQuery will have the fix for the custom projection issue, but you are right your extension should work better than the current AsSplitQuery. Sorry I got this confused.
